main: net.whirvis.mc.discraft.DiscraftPlugin
name: Discraft
version: 0.0.1-SNAPSHOT
api-version: 1.17

author: Whirvis
description: A plugin which links Minecraft and Discord servers together
website: discraft.whirvis.net